package IU;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Gabriel, Gustavo, Igor
 */
public class TelaCadastroImovel extends javax.swing.JDialog {
      
      private int diaConst, mesConst, anoConst, diaPag, mesPag, anoPag, dorm, banh, garg, andar;
      private String cod, end;
      float areaTot, areaConst, iptu, valorVenda, valorAluguel, impostoFed, valorCond;

      public int getDiaConst() {
            return diaConst;
      }

      public int getMesConst() {
            return mesConst;
      }

      public int getAnoConst() {
            return anoConst;
      }

      public int getDiaPag() {
            return diaPag;
      }

      public int getMesPag() {
            return mesPag;
      }

      public int getAnoPag() {
            return anoPag;
      }

      public int getDorm() {
            return dorm;
      }

      public int getBanh() {
            return banh;
      }

      public int getGarg() {
            return garg;
      }

      public int getAndar() {
            return andar;
      }

      public String getCod() {
            return cod;
      }

      public String getEnd() {
            return end;
      }

      public float getAreaTot() {
            return areaTot;
      }

      public float getAreaConst() {
            return areaConst;
      }

      public float getIptu() {
            return iptu;
      }

      public float getValorVenda() {
            return valorVenda;
      }

      public float getValorAluguel() {
            return valorAluguel;
      }

      public float getImpostoFed() {
            return impostoFed;
      }

      public float getValorCond() {
            return valorCond;
      }

      
      
      /**
       * Creates new form TelaCadastroCliente
       */
      public TelaCadastroImovel(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanelTitulo = new javax.swing.JPanel();
            jLabelTitulo = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jFormattedTextFieldCod = new javax.swing.JFormattedTextField();
            SimpleDateFormat model = new SimpleDateFormat("dd.MM.yy");
            jSpinnerDataConst = new javax.swing.JSpinner(new SpinnerDateModel());
            jSpinnerDataConst.setEditor(new JSpinner.DateEditor(jSpinnerDataConst, model.toPattern()));
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextAreaEndereco = new javax.swing.JTextArea();
            SimpleDateFormat model1 = new SimpleDateFormat("dd.MM.yy");
            jSpinnerDataPagamento = new javax.swing.JSpinner(new SpinnerDateModel());
            jSpinnerDataPagamento.setEditor(new JSpinner.DateEditor(jSpinnerDataConst, model1.toPattern()));
            jLabel10 = new javax.swing.JLabel();
            jButtonCadastrar = new javax.swing.JButton();
            jSpinnerValorVenda = new javax.swing.JSpinner();
            jLabel7 = new javax.swing.JLabel();
            jSpinnerImpostoFed = new javax.swing.JSpinner();
            jLabel9 = new javax.swing.JLabel();
            jSpinnerAreaTot = new javax.swing.JSpinner();
            jLabel11 = new javax.swing.JLabel();
            jSpinnerAreaConst = new javax.swing.JSpinner();
            jLabel12 = new javax.swing.JLabel();
            jSpinnerCondominio = new javax.swing.JSpinner();
            jLabel13 = new javax.swing.JLabel();
            jLabel14 = new javax.swing.JLabel();
            jSpinnerAndar = new javax.swing.JSpinner();
            jLabel15 = new javax.swing.JLabel();
            jSpinnerQuartos = new javax.swing.JSpinner();
            jLabel16 = new javax.swing.JLabel();
            jSpinnerBanheiros = new javax.swing.JSpinner();
            jSpinnerGaragem = new javax.swing.JSpinner();
            jLabel17 = new javax.swing.JLabel();
            jLabel18 = new javax.swing.JLabel();
            jSpinnerValorAluguel = new javax.swing.JSpinner();
            jLabel19 = new javax.swing.JLabel();
            jSpinnerIPTU = new javax.swing.JSpinner();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
            setResizable(false);

            jLabelTitulo.setFont(jLabelTitulo.getFont().deriveFont((float)30));
            jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabelTitulo.setText("Cadastro de Imóvel");

            javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
            jPanelTitulo.setLayout(jPanelTituloLayout);
            jPanelTituloLayout.setHorizontalGroup(
                  jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanelTituloLayout.setVerticalGroup(
                  jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );

            jLabel1.setText("Código do Imóvel");

            jFormattedTextFieldCod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
            jFormattedTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jFormattedTextFieldCodActionPerformed(evt);
                  }
            });

            jSpinnerDataConst.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1669669959618L), new java.util.Date(-1577912400000L), new java.util.Date(1669669959618L), java.util.Calendar.DAY_OF_MONTH));

            jLabel5.setText("Data da Construção");

            jLabel6.setText("Endereço");

            jTextAreaEndereco.setColumns(20);
            jTextAreaEndereco.setLineWrap(true);
            jTextAreaEndereco.setRows(1);
            jScrollPane1.setViewportView(jTextAreaEndereco);

            jSpinnerDataPagamento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1669669959618L), new java.util.Date(-1577912400000L), new java.util.Date(1669669959618L), java.util.Calendar.DAY_OF_MONTH));

            jLabel10.setText("Data de Pagamento Mensal");

            jButtonCadastrar.setText("Cadastrar");
            jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonCadastrarActionPerformed(evt);
                  }
            });

            jSpinnerValorVenda.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 10.0f));

            jLabel7.setText("Valor Venda");

            jSpinnerImpostoFed.setModel(new javax.swing.SpinnerNumberModel(-1.0f, null, null, 10.0f));

            jLabel9.setText("Taxa de Imposto Federal (se houver)");

            jSpinnerAreaTot.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 0.5f));

            jLabel11.setText("Área Total");

            jSpinnerAreaConst.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 0.5f));

            jLabel12.setText("Área Construída");

            jSpinnerCondominio.setModel(new javax.swing.SpinnerNumberModel(-1.0f, null, null, 10.0f));

            jLabel13.setText("Valor do Condomínio (se houver)");

            jLabel14.setText("Andar (se houver)");

            jSpinnerAndar.setModel(new javax.swing.SpinnerNumberModel(-1.0f, null, null, 10.0f));

            jLabel15.setText("Nº de Quartos");

            jSpinnerQuartos.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

            jLabel16.setText("Nº de Banheiros");

            jSpinnerBanheiros.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

            jSpinnerGaragem.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

            jLabel17.setText("Vagas Garagem");

            jLabel18.setText("Valor Aluguel");

            jSpinnerValorAluguel.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 10.0f));

            jLabel19.setText("Valor IPTU");

            jSpinnerIPTU.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 10.0f));

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerImpostoFed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel13))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel14)))
                                          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                                .addComponent(jFormattedTextFieldCod))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jSpinnerAreaTot, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jSpinnerAreaConst, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jSpinnerQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jSpinnerBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jSpinnerGaragem)
                                                      .addComponent(jLabel17)))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jSpinnerDataConst, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                      .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel10)))
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                      .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jSpinnerIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel18))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jLabel7))))
                                    .addContainerGap(54, Short.MAX_VALUE))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                                          .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(6, 6, 6)
                                    .addComponent(jFormattedTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(jSpinnerAreaTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel15)
                                          .addComponent(jLabel16)
                                          .addComponent(jLabel17)
                                          .addComponent(jLabel12)
                                          .addComponent(jLabel11)
                                          .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addComponent(jSpinnerQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jSpinnerBanheiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jSpinnerGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addComponent(jSpinnerAreaConst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jSpinnerDataConst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jLabel10)
                                          .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinnerDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jSpinnerIPTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jLabel19)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinnerValorAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinnerValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSpinnerImpostoFed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(jLabel13)
                              .addComponent(jLabel14)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(jSpinnerCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(jSpinnerAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
            // TODO add your handling code here:
            cod = jFormattedTextFieldCod.getText();
           end = jTextAreaEndereco.getText();
           areaTot = (float) jSpinnerAreaTot.getValue();
           areaConst = (float) jSpinnerAreaConst.getValue();
           dorm = (int) jSpinnerQuartos.getValue();
           banh = (int) jSpinnerBanheiros.getValue();
           garg = (int) jSpinnerGaragem.getValue();
           iptu = (float) jSpinnerIPTU.getValue();
           valorVenda = (float) jSpinnerValorVenda.getValue();
           valorAluguel = (float) jSpinnerValorAluguel.getValue();
           try{
                 impostoFed = (float) jSpinnerImpostoFed.getValue();
           } catch (Exception e){
                 impostoFed = -1;
           }
           
           try{
                 andar = (int) jSpinnerAndar.getValue();
           } catch(Exception e) {
                 andar = -1;
           }
           try {
                 valorCond = (float) jSpinnerCondominio.getValue();
           } catch (Exception e){
                 valorCond = -1;
           }
            
           LocalDate dataConst = ((Date) jSpinnerDataConst.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
           diaConst = dataConst.getDayOfMonth();
           mesConst = dataConst.getMonthValue();
           anoConst = dataConst.getYear();
           LocalDate dataCad = ((Date) jSpinnerDataPagamento.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
           diaPag = dataCad.getDayOfMonth();
           mesPag = dataCad.getMonthValue();
           anoPag = dataCad.getYear();
            
            boolean preenchidos = false;
            if(!cod.equals("") && !end.equals("") && !(areaTot == 0) && !(areaConst == 0) && !(valorAluguel == 0) && !(valorVenda == 0)){
                  preenchidos = true;
            }
            if(preenchidos){
                  this.setVisible(false);
            } else {
                  JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos corretamente");
            }
      }//GEN-LAST:event_jButtonCadastrarActionPerformed

      private void jFormattedTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jFormattedTextFieldCodActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButtonCadastrar;
      private javax.swing.JFormattedTextField jFormattedTextFieldCod;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel14;
      private javax.swing.JLabel jLabel15;
      private javax.swing.JLabel jLabel16;
      private javax.swing.JLabel jLabel17;
      private javax.swing.JLabel jLabel18;
      private javax.swing.JLabel jLabel19;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JLabel jLabelTitulo;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanelTitulo;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JSpinner jSpinnerAndar;
      private javax.swing.JSpinner jSpinnerAreaConst;
      private javax.swing.JSpinner jSpinnerAreaTot;
      private javax.swing.JSpinner jSpinnerBanheiros;
      private javax.swing.JSpinner jSpinnerCondominio;
      private javax.swing.JSpinner jSpinnerDataConst;
      private javax.swing.JSpinner jSpinnerDataPagamento;
      private javax.swing.JSpinner jSpinnerGaragem;
      private javax.swing.JSpinner jSpinnerIPTU;
      private javax.swing.JSpinner jSpinnerImpostoFed;
      private javax.swing.JSpinner jSpinnerQuartos;
      private javax.swing.JSpinner jSpinnerValorAluguel;
      private javax.swing.JSpinner jSpinnerValorVenda;
      private javax.swing.JTextArea jTextAreaEndereco;
      // End of variables declaration//GEN-END:variables
}
