package IU;

import javax.swing.JOptionPane;



/**
 *
 * @author Gabriel, Gustavo, Igor
 */
public class TelaVenda extends javax.swing.JDialog {
      private String nome, bandeira, codImovel, codCorretor, codCliente, numero, codVenda;

      public String getNome() {
            return nome;
      }

      public String getBandeira() {
            return bandeira;
      }

      public String getCodImovel() {
            return codImovel;
      }

      public String getCodCorretor() {
            return codCorretor;
      }

      public String getCodCliente() {
            return codCliente;
      }

      public String getNumero() {
            return numero;
      }
    
      public String getCodVenda(){
            return codVenda;
      }
      /**
       * Creates new form TelaCadastroCliente
       */
      public TelaVenda(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanelTitulo = new javax.swing.JPanel();
            jLabelTitulo = new javax.swing.JLabel();
            jFormattedTextFieldCodImovel = new javax.swing.JFormattedTextField();
            jLabel2 = new javax.swing.JLabel();
            jFormattedTextFieldCodCliente = new javax.swing.JFormattedTextField();
            jLabel3 = new javax.swing.JLabel();
            jFormattedTextFieldCodCorretor = new javax.swing.JFormattedTextField();
            jLabel4 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jTextFieldNome = new javax.swing.JTextField();
            jTextFieldBandeira = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            jFormattedTextFieldNumero = new javax.swing.JFormattedTextField();
            jLabel6 = new javax.swing.JLabel();
            jButtonRegistrar = new javax.swing.JButton();
            jLabel7 = new javax.swing.JLabel();
            jFormattedTextFieldCodVenda = new javax.swing.JFormattedTextField();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
            setResizable(false);

            jLabelTitulo.setFont(jLabelTitulo.getFont().deriveFont((float)30));
            jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabelTitulo.setText("Registrar Venda");

            javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
            jPanelTitulo.setLayout(jPanelTituloLayout);
            jPanelTituloLayout.setHorizontalGroup(
                  jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanelTituloLayout.setVerticalGroup(
                  jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );

            jFormattedTextFieldCodImovel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
            jFormattedTextFieldCodImovel.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jFormattedTextFieldCodImovelActionPerformed(evt);
                  }
            });

            jLabel2.setText("Código Imóvel");

            jFormattedTextFieldCodCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
            jFormattedTextFieldCodCliente.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jFormattedTextFieldCodClienteActionPerformed(evt);
                  }
            });

            jLabel3.setText("Código Cliente");

            jFormattedTextFieldCodCorretor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
            jFormattedTextFieldCodCorretor.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jFormattedTextFieldCodCorretorActionPerformed(evt);
                  }
            });

            jLabel4.setText("Código Corretor");

            jLabel1.setText("Nome no Cartão");

            jLabel5.setText("Bandeira do Cartão");

            jFormattedTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
            jFormattedTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jFormattedTextFieldNumeroActionPerformed(evt);
                  }
            });

            jLabel6.setText("Número do Cartão");

            jButtonRegistrar.setText("Registrar");
            jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButtonRegistrarActionPerformed(evt);
                  }
            });

            jLabel7.setText("Código da Venda");

            jFormattedTextFieldCodVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
            jFormattedTextFieldCodVenda.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jFormattedTextFieldCodVendaActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jFormattedTextFieldCodImovel)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                      .addGap(18, 18, 18)
                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jFormattedTextFieldCodCliente)
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jFormattedTextFieldCodCorretor)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextFieldBandeira)
                                    .addComponent(jTextFieldNome)
                                    .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(jFormattedTextFieldNumero, javax.swing.GroupLayout.Alignment.LEADING))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(jFormattedTextFieldCodVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                              .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextFieldCodImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextFieldCodCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jFormattedTextFieldCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void jFormattedTextFieldCodImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodImovelActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jFormattedTextFieldCodImovelActionPerformed

      private void jFormattedTextFieldCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodClienteActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jFormattedTextFieldCodClienteActionPerformed

      private void jFormattedTextFieldCodCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodCorretorActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jFormattedTextFieldCodCorretorActionPerformed

      private void jFormattedTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNumeroActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jFormattedTextFieldNumeroActionPerformed

      private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
            // TODO add your handling code here:
            codVenda = jFormattedTextFieldCodVenda.getText();
            numero =  jFormattedTextFieldNumero.getText();
            codImovel = jFormattedTextFieldCodImovel.getText();
            codCliente = jFormattedTextFieldCodCliente.getText();
            codCorretor = jFormattedTextFieldCodCorretor.getText();
            nome = jTextFieldNome.getText();
            bandeira = jTextFieldBandeira.getText();
            
            boolean preenchidos = false;
            if(!codVenda.equals("") && !numero.equals("") && !codImovel.equals("") && !codCliente.equals("") && !codCorretor.equals("") && !nome.equals("") && !bandeira.equals("")) preenchidos = true;
            if(preenchidos){
                  this.setVisible(false);
            } else {
                  JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos corretamente");
            }
      }//GEN-LAST:event_jButtonRegistrarActionPerformed

      private void jFormattedTextFieldCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCodVendaActionPerformed
            // TODO add your handling code here:
      }//GEN-LAST:event_jFormattedTextFieldCodVendaActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButtonRegistrar;
      private javax.swing.JFormattedTextField jFormattedTextFieldCodCliente;
      private javax.swing.JFormattedTextField jFormattedTextFieldCodCorretor;
      private javax.swing.JFormattedTextField jFormattedTextFieldCodImovel;
      private javax.swing.JFormattedTextField jFormattedTextFieldCodVenda;
      private javax.swing.JFormattedTextField jFormattedTextFieldNumero;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabelTitulo;
      private javax.swing.JPanel jPanelTitulo;
      private javax.swing.JTextField jTextFieldBandeira;
      private javax.swing.JTextField jTextFieldNome;
      // End of variables declaration//GEN-END:variables
}
