package IU;

import Controlador.Controlador;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel, Gustavo, Igor
 */
public class TelaInicial extends javax.swing.JFrame {

      private Controlador control;
      
      /**
       * Creates new form TelaInicial
       */
      public TelaInicial() {
            initComponents();
            control = new Controlador("Imobiliária FCT", "Rua 1 de Abril, 900, Centro, Presidente Prudente-SP");
            try {
                  control.atualizarImobiliaria();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanelTitulo = new javax.swing.JPanel();
            jLabelTitulo = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jMenuBarMenu = new javax.swing.JMenuBar();
            jMenuCadastro = new javax.swing.JMenu();
            jMenuItemCadCliente = new javax.swing.JMenuItem();
            jMenuItemCadCorretor = new javax.swing.JMenuItem();
            jMenuItemCadImovel = new javax.swing.JMenuItem();
            jMenuItemCadSeguro = new javax.swing.JMenuItem();
            jMenuImovel = new javax.swing.JMenu();
            jMenuItemAddVenda = new javax.swing.JMenuItem();
            jMenuItemAddAluguel = new javax.swing.JMenuItem();
            jMenuRelatorio = new javax.swing.JMenu();
            jMenuReImovel = new javax.swing.JMenu();
            jMenuItemImoveis = new javax.swing.JMenuItem();
            jMenuItemCasas = new javax.swing.JMenuItem();
            jMenuItemApts = new javax.swing.JMenuItem();
            jMenuItemComerciais = new javax.swing.JMenuItem();
            jMenuItemImoveisDispo = new javax.swing.JMenuItem();
            jMenuItemIndispo = new javax.swing.JMenuItem();
            jMenuItemAtrasado = new javax.swing.JMenuItem();
            jMenuItemCasaAlugada = new javax.swing.JMenuItem();
            jMenuItemAptAlugado = new javax.swing.JMenuItem();
            jMenuItemComercialAlugado = new javax.swing.JMenuItem();
            jMenuItemImoveisAlugCliente = new javax.swing.JMenuItem();
            jMenuItemImoveisCompCliente = new javax.swing.JMenuItem();
            jMenu1 = new javax.swing.JMenu();
            jMenuItemClientes = new javax.swing.JMenuItem();
            jMenuItemCorretores = new javax.swing.JMenuItem();
            jMenuItemFuncMes = new javax.swing.JMenuItem();
            jMenuItemClienteAtrasado = new javax.swing.JMenuItem();
            jMenuAlgueis = new javax.swing.JMenu();
            jMenuItemAlugueis = new javax.swing.JMenuItem();
            jMenuItemAlugFinal = new javax.swing.JMenuItem();
            jMenuItemAlugNaoFinal = new javax.swing.JMenuItem();
            jMenuVendas = new javax.swing.JMenu();
            jMenuItemRelVendas = new javax.swing.JMenuItem();
            jMenuItemLucroVendas = new javax.swing.JMenuItem();
            jMenuItemLucroVendasMes = new javax.swing.JMenuItem();
            jMenuSeguros = new javax.swing.JMenu();
            jMenuItemTiposSeguros = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Sistema Imobiliária FCT");
            setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
            setResizable(false);

            jLabelTitulo.setFont(new java.awt.Font("OCR A Extended", 0, 60)); // NOI18N
            jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabelTitulo.setText("IMOBILIÁRIA FCT");

            jLabel1.setFont(new java.awt.Font("SansSerif", 0, 90)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("🏠");
            jLabel1.setToolTipText("");

            javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
            jPanelTitulo.setLayout(jPanelTituloLayout);
            jPanelTituloLayout.setHorizontalGroup(
                  jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                  .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanelTituloLayout.setVerticalGroup(
                  jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
            );

            jMenuBarMenu.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

            jMenuCadastro.setBorder(null);
            jMenuCadastro.setText("Cadastro");
            jMenuCadastro.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemCadCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCadCliente.setText("Cadastrar Cliente");
            jMenuItemCadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCadClienteActionPerformed(evt);
                  }
            });
            jMenuCadastro.add(jMenuItemCadCliente);

            jMenuItemCadCorretor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCadCorretor.setText("Cadastrar Corretor");
            jMenuItemCadCorretor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCadCorretor.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCadCorretorActionPerformed(evt);
                  }
            });
            jMenuCadastro.add(jMenuItemCadCorretor);

            jMenuItemCadImovel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCadImovel.setText("Cadastrar Imóvel");
            jMenuItemCadImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCadImovel.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCadImovelActionPerformed(evt);
                  }
            });
            jMenuCadastro.add(jMenuItemCadImovel);

            jMenuItemCadSeguro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCadSeguro.setText("Cadastrar Seguro");
            jMenuItemCadSeguro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCadSeguro.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCadSeguroActionPerformed(evt);
                  }
            });
            jMenuCadastro.add(jMenuItemCadSeguro);

            jMenuBarMenu.add(jMenuCadastro);

            jMenuImovel.setBorder(null);
            jMenuImovel.setText("Imóvel");
            jMenuImovel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemAddVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAddVenda.setText("Registrar Venda");
            jMenuItemAddVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAddVenda.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAddVendaActionPerformed(evt);
                  }
            });
            jMenuImovel.add(jMenuItemAddVenda);

            jMenuItemAddAluguel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAddAluguel.setText("Contratar Aluguel");
            jMenuItemAddAluguel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAddAluguel.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAddAluguelActionPerformed(evt);
                  }
            });
            jMenuImovel.add(jMenuItemAddAluguel);

            jMenuBarMenu.add(jMenuImovel);

            jMenuRelatorio.setBorder(null);
            jMenuRelatorio.setText("Relatório");
            jMenuRelatorio.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuReImovel.setText("Imóveis");
            jMenuReImovel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemImoveis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemImoveis.setText("Listar Imóveis");
            jMenuItemImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemImoveis.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemImoveisActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemImoveis);

            jMenuItemCasas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCasas.setText("Listar Casas Residencias");
            jMenuItemCasas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCasas.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCasasActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemCasas);

            jMenuItemApts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemApts.setText("Listar Apartamentos Residenciais");
            jMenuItemApts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemApts.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAptsActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemApts);

            jMenuItemComerciais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemComerciais.setText("Listar Imóveis Comerciais");
            jMenuItemComerciais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemComerciais.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemComerciaisActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemComerciais);

            jMenuItemImoveisDispo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemImoveisDispo.setText("Listar Imóveis disponíveis");
            jMenuItemImoveisDispo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemImoveisDispo.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemImoveisDispoActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemImoveisDispo);

            jMenuItemIndispo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemIndispo.setText("Listar Imóveis indísponiveis");
            jMenuItemIndispo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemIndispo.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemIndispoActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemIndispo);

            jMenuItemAtrasado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAtrasado.setText("Listar Imóveis com Aluguel atrasado");
            jMenuItemAtrasado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAtrasado.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAtrasadoActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemAtrasado);

            jMenuItemCasaAlugada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCasaAlugada.setText("Listar Casas Residenciais alugadas");
            jMenuItemCasaAlugada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCasaAlugada.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCasaAlugadaActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemCasaAlugada);

            jMenuItemAptAlugado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAptAlugado.setText("Listar Apartamentos Residenciais alugados");
            jMenuItemAptAlugado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAptAlugado.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAptAlugadoActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemAptAlugado);

            jMenuItemComercialAlugado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemComercialAlugado.setText("Listar Imóveis Comerciais alugados");
            jMenuItemComercialAlugado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemComercialAlugado.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemComercialAlugadoActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemComercialAlugado);

            jMenuItemImoveisAlugCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemImoveisAlugCliente.setText("Listar Imóveis alugados por Cliente");
            jMenuItemImoveisAlugCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemImoveisAlugCliente.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemImoveisAlugClienteActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemImoveisAlugCliente);

            jMenuItemImoveisCompCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemImoveisCompCliente.setText("Listar Imóveis comprados por Cliente");
            jMenuItemImoveisCompCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemImoveisCompCliente.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemImoveisCompClienteActionPerformed(evt);
                  }
            });
            jMenuReImovel.add(jMenuItemImoveisCompCliente);

            jMenuRelatorio.add(jMenuReImovel);

            jMenu1.setText("Usuários");
            jMenu1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemClientes.setText("Listar Clientes");
            jMenuItemClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemClientesActionPerformed(evt);
                  }
            });
            jMenu1.add(jMenuItemClientes);

            jMenuItemCorretores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemCorretores.setText("Listar Corretores");
            jMenuItemCorretores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemCorretores.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemCorretoresActionPerformed(evt);
                  }
            });
            jMenu1.add(jMenuItemCorretores);

            jMenuItemFuncMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemFuncMes.setText("Listar Funcionários do Mês");
            jMenuItemFuncMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemFuncMes.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemFuncMesActionPerformed(evt);
                  }
            });
            jMenu1.add(jMenuItemFuncMes);

            jMenuItemClienteAtrasado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemClienteAtrasado.setText("Listar Clientes com Aluguel atrasado ");
            jMenuItemClienteAtrasado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemClienteAtrasado.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemClienteAtrasadoActionPerformed(evt);
                  }
            });
            jMenu1.add(jMenuItemClienteAtrasado);

            jMenuRelatorio.add(jMenu1);

            jMenuAlgueis.setText("Alugueis");
            jMenuAlgueis.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemAlugueis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAlugueis.setText("Listar Alugueis");
            jMenuItemAlugueis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAlugueis.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAlugueisActionPerformed(evt);
                  }
            });
            jMenuAlgueis.add(jMenuItemAlugueis);

            jMenuItemAlugFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAlugFinal.setText("Listar Alugueis finalizados");
            jMenuItemAlugFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAlugFinal.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAlugFinalActionPerformed(evt);
                  }
            });
            jMenuAlgueis.add(jMenuItemAlugFinal);

            jMenuItemAlugNaoFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemAlugNaoFinal.setText("Listar Alugueis não finalizados");
            jMenuItemAlugNaoFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemAlugNaoFinal.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAlugNaoFinalActionPerformed(evt);
                  }
            });
            jMenuAlgueis.add(jMenuItemAlugNaoFinal);

            jMenuRelatorio.add(jMenuAlgueis);

            jMenuVendas.setText("Vendas");
            jMenuVendas.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemRelVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemRelVendas.setText("Listar Vendas");
            jMenuItemRelVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemRelVendas.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemRelVendasActionPerformed(evt);
                  }
            });
            jMenuVendas.add(jMenuItemRelVendas);

            jMenuItemLucroVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemLucroVendas.setText("Listar Lucro e Vendas");
            jMenuItemLucroVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemLucroVendas.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemLucroVendasActionPerformed(evt);
                  }
            });
            jMenuVendas.add(jMenuItemLucroVendas);

            jMenuItemLucroVendasMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemLucroVendasMes.setText("Listar Vendas e Lucro por mês");
            jMenuItemLucroVendasMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemLucroVendasMes.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemLucroVendasMesActionPerformed(evt);
                  }
            });
            jMenuVendas.add(jMenuItemLucroVendasMes);

            jMenuRelatorio.add(jMenuVendas);

            jMenuSeguros.setText("Seguros");
            jMenuSeguros.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

            jMenuItemTiposSeguros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            jMenuItemTiposSeguros.setText("Listar tipos de Seguros");
            jMenuItemTiposSeguros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jMenuItemTiposSeguros.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemTiposSegurosActionPerformed(evt);
                  }
            });
            jMenuSeguros.add(jMenuItemTiposSeguros);

            jMenuRelatorio.add(jMenuSeguros);

            jMenuBarMenu.add(jMenuRelatorio);

            setJMenuBar(jMenuBarMenu);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(99, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
            // TODO add your handling code here:
            TelaCadastroCliente telaCadCliente = new TelaCadastroCliente(this, true);
            telaCadCliente.setLocationRelativeTo(this);
            telaCadCliente.setVisible(true);
            control.cadastrarCliente(Integer.parseInt(telaCadCliente.getCod()), telaCadCliente.getNome(), telaCadCliente.getCpf(), telaCadCliente.getRg(),  telaCadCliente.getDiaNasc(), telaCadCliente.getMesNasc(), telaCadCliente.getAnoNasc(), telaCadCliente.getEndereco(), telaCadCliente.getCep(), telaCadCliente.getTelefone(), telaCadCliente.getEmail() , telaCadCliente.getDiaCad(), telaCadCliente.getMesCad(), telaCadCliente.getAnoCad());
            try {
                  control.atualizarArquivos();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
      }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

      private void jMenuItemCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCasasActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarCasas());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemCasasActionPerformed

      private void jMenuItemComerciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComerciaisActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarComerciais());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemComerciaisActionPerformed

      private void jMenuItemIndispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIndispoActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarImoveisIndisponiveis());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemIndispoActionPerformed

      private void jMenuItemCasaAlugadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCasaAlugadaActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarCasasAlugadas());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemCasaAlugadaActionPerformed

      private void jMenuItemCadImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadImovelActionPerformed
            // TODO add your handling code here:
            TelaCadastroImovel telaCadImovel = new TelaCadastroImovel(this, true);
            telaCadImovel.setLocationRelativeTo(this);
            telaCadImovel.setVisible(true);
            control.cadastrarImovel(Integer.parseInt(telaCadImovel.getCod()), telaCadImovel.getEnd(), LocalDate.of(telaCadImovel.getAnoConst(), telaCadImovel.getMesConst(), telaCadImovel.getDiaConst()), telaCadImovel.getAreaTot(), telaCadImovel.getAreaConst(), telaCadImovel.getDorm(), telaCadImovel.getBanh(), telaCadImovel.getGarg(), telaCadImovel.getIptu(), telaCadImovel.getValorVenda(), telaCadImovel.getValorAluguel(), telaCadImovel.getImpostoFed(), telaCadImovel.getAndar(), telaCadImovel.valorCond);
            try {
                  control.atualizarArquivos();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
      }//GEN-LAST:event_jMenuItemCadImovelActionPerformed

      private void jMenuItemImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImoveisActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarImoveis());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemImoveisActionPerformed

      private void jMenuItemImoveisAlugClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImoveisAlugClienteActionPerformed
            // TODO add your handling code here:
            TelaCliente clienteTela = new TelaCliente(this, true);
            clienteTela.setLocationRelativeTo(this);
            clienteTela.setVisible(true);
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarImoveisAlugadosCliente(clienteTela.getCodCliente()));
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemImoveisAlugClienteActionPerformed

      private void jMenuItemImoveisDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImoveisDispoActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarImoveisDisponiveis());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemImoveisDispoActionPerformed

      private void jMenuItemCadSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadSeguroActionPerformed
            // TODO add your handling code here:
            TelaCadastroSeguro cadSeg = new TelaCadastroSeguro(this, true);
            cadSeg.setLocationRelativeTo(this);
            cadSeg.setVisible(true);
            control.cadastrarSeguro(Integer.parseInt(cadSeg.getCod()), cadSeg.getNome(), cadSeg.getTipo(), cadSeg.getDescricao(), cadSeg.getValor());
            try {
                  control.atualizarArquivos();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
      }//GEN-LAST:event_jMenuItemCadSeguroActionPerformed

      private void jMenuItemCadCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadCorretorActionPerformed
            // TODO add your handling code here:
            TelaCadastroCorretor telaCadCorretor= new TelaCadastroCorretor(this, true);
            telaCadCorretor.setLocationRelativeTo(this);
            telaCadCorretor.setVisible(true);
            control.cadastrarCorretor(Integer.parseInt(telaCadCorretor.getCod()), telaCadCorretor.getNome(), telaCadCorretor.getCpf(), telaCadCorretor.getRg(),  telaCadCorretor.getDiaNasc(), telaCadCorretor.getMesNasc(), telaCadCorretor.getAnoNasc(), telaCadCorretor.getEndereco(), telaCadCorretor.getCep(), telaCadCorretor.getTelefone(), telaCadCorretor.getEmail(), telaCadCorretor.getCreci(), Float.parseFloat(telaCadCorretor.getSalario()), telaCadCorretor.getPis(), telaCadCorretor.getDiaCad(), telaCadCorretor.getMesCad(), telaCadCorretor.getAnoCad());
            try {
                  control.atualizarArquivos();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            
      }//GEN-LAST:event_jMenuItemCadCorretorActionPerformed

      private void jMenuItemCorretoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCorretoresActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarCorretores());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemCorretoresActionPerformed

      private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarClientes());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemClientesActionPerformed

      private void jMenuItemFuncMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncMesActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarFuncionariosMes());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemFuncMesActionPerformed

      private void jMenuItemClienteAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteAtrasadoActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.clientesAluguelAtrasado());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemClienteAtrasadoActionPerformed

      private void jMenuItemAptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAptsActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarApartamentos());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemAptsActionPerformed

      private void jMenuItemAtrasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtrasadoActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarImoveisAtrasados());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemAtrasadoActionPerformed

      private void jMenuItemAptAlugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAptAlugadoActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarApartamentosAlugados());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemAptAlugadoActionPerformed

      private void jMenuItemComercialAlugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComercialAlugadoActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarComerciaisAlugados());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemComercialAlugadoActionPerformed

      private void jMenuItemImoveisCompClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImoveisCompClienteActionPerformed
            // TODO add your handling code here:
            TelaCliente clienteTela = new TelaCliente(this, true);
            clienteTela.setLocationRelativeTo(this);
            clienteTela.setVisible(true);
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarImoveisCompradosCliente(clienteTela.getCodCliente()));
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemImoveisCompClienteActionPerformed

      private void jMenuItemAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlugueisActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarAlugueis());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemAlugueisActionPerformed

      private void jMenuItemAlugFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlugFinalActionPerformed
            // TODO add your handling code here:
             TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarAlugueisFinalizados());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemAlugFinalActionPerformed

      private void jMenuItemAlugNaoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlugNaoFinalActionPerformed
            // TODO add your handling code here:
             TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarAlugueisNaoFinalizados());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemAlugNaoFinalActionPerformed

      private void jMenuItemRelVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelVendasActionPerformed
            // TODO add your handling code here:
             TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarVendas());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemRelVendasActionPerformed

      private void jMenuItemLucroVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLucroVendasActionPerformed
            // TODO add your handling code here:
             TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarVendasLucro());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemLucroVendasActionPerformed

      private void jMenuItemLucroVendasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLucroVendasMesActionPerformed
            // TODO add your handling code here:
            TelaMes vendaMes = new TelaMes(this, true);
            vendaMes.setLocationRelativeTo(this);
            vendaMes.setVisible(true);
            String s = "";
            try {
                  s = control.listarVendasLucroMes(vendaMes.getMes(), vendaMes.getAno());
            } catch (Exception e) {
                  s = "Nenhuma venda encontrada no mês digitado";
            }
            TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemLucroVendasMesActionPerformed

      private void jMenuItemTiposSegurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTiposSegurosActionPerformed
            // TODO add your handling code here:
            TelaRelatorio relatorio = new TelaRelatorio(this, true, control.listarTiposSeguros());
            relatorio.setLocationRelativeTo(this);
            relatorio.setVisible(true);
      }//GEN-LAST:event_jMenuItemTiposSegurosActionPerformed

      private void jMenuItemAddVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddVendaActionPerformed
            // TODO add your handling code here:
            TelaVenda venda = new TelaVenda(this, true);
            venda.setLocationRelativeTo(this);
            venda.setVisible(true);
            if(control.vender(Integer.parseInt(venda.getCodVenda()), Integer.parseInt(venda.getCodImovel()), Integer.parseInt(venda.getCodCliente()), Integer.parseInt(venda.getCodCorretor()), venda.getNome(), venda.getBandeira(), venda.getNumero())){
                  JOptionPane.showMessageDialog(rootPane, "DEu");
            }
            try {
                  control.atualizarArquivos();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
      }//GEN-LAST:event_jMenuItemAddVendaActionPerformed

      private void jMenuItemAddAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddAluguelActionPerformed
            // TODO add your handling code here:
            TelaAluguel aluguel = new TelaAluguel(this, true);
            aluguel.setLocationRelativeTo(this);
            aluguel.setVisible(true);
            control.alugar(Integer.parseInt(aluguel.getCodAlug()), Integer.parseInt(aluguel.getCodImovel()), Integer.parseInt(aluguel.getCodCliente()), Integer.parseInt(aluguel.getCodCorretor()), aluguel.getDiaDev(), aluguel.getMesDev(), aluguel.getAnoDev(), aluguel.getDiaPag(), aluguel.getMesPag(), aluguel.getAnoPag(), aluguel.getSegs(), aluguel.getTipoPag(), aluguel.getNome(), aluguel.getBandeira(), aluguel.getNumero());
            try {
                  control.atualizarArquivos();
            } catch (IOException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
      }//GEN-LAST:event_jMenuItemAddAluguelActionPerformed


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabelTitulo;
      private javax.swing.JMenu jMenu1;
      private javax.swing.JMenu jMenuAlgueis;
      private javax.swing.JMenuBar jMenuBarMenu;
      private javax.swing.JMenu jMenuCadastro;
      private javax.swing.JMenu jMenuImovel;
      private javax.swing.JMenuItem jMenuItemAddAluguel;
      private javax.swing.JMenuItem jMenuItemAddVenda;
      private javax.swing.JMenuItem jMenuItemAlugFinal;
      private javax.swing.JMenuItem jMenuItemAlugNaoFinal;
      private javax.swing.JMenuItem jMenuItemAlugueis;
      private javax.swing.JMenuItem jMenuItemAptAlugado;
      private javax.swing.JMenuItem jMenuItemApts;
      private javax.swing.JMenuItem jMenuItemAtrasado;
      private javax.swing.JMenuItem jMenuItemCadCliente;
      private javax.swing.JMenuItem jMenuItemCadCorretor;
      private javax.swing.JMenuItem jMenuItemCadImovel;
      private javax.swing.JMenuItem jMenuItemCadSeguro;
      private javax.swing.JMenuItem jMenuItemCasaAlugada;
      private javax.swing.JMenuItem jMenuItemCasas;
      private javax.swing.JMenuItem jMenuItemClienteAtrasado;
      private javax.swing.JMenuItem jMenuItemClientes;
      private javax.swing.JMenuItem jMenuItemComerciais;
      private javax.swing.JMenuItem jMenuItemComercialAlugado;
      private javax.swing.JMenuItem jMenuItemCorretores;
      private javax.swing.JMenuItem jMenuItemFuncMes;
      private javax.swing.JMenuItem jMenuItemImoveis;
      private javax.swing.JMenuItem jMenuItemImoveisAlugCliente;
      private javax.swing.JMenuItem jMenuItemImoveisCompCliente;
      private javax.swing.JMenuItem jMenuItemImoveisDispo;
      private javax.swing.JMenuItem jMenuItemIndispo;
      private javax.swing.JMenuItem jMenuItemLucroVendas;
      private javax.swing.JMenuItem jMenuItemLucroVendasMes;
      private javax.swing.JMenuItem jMenuItemRelVendas;
      private javax.swing.JMenuItem jMenuItemTiposSeguros;
      private javax.swing.JMenu jMenuReImovel;
      private javax.swing.JMenu jMenuRelatorio;
      private javax.swing.JMenu jMenuSeguros;
      private javax.swing.JMenu jMenuVendas;
      private javax.swing.JPanel jPanelTitulo;
      // End of variables declaration//GEN-END:variables
}
