package IU;

/**
 *
 * @author Gabriel, Gustavo, Igor
 */
public class TelaRelatorio extends javax.swing.JDialog {
      private String relatorio; 

      public void setRelatorio(String relatorio) {
            this.relatorio = relatorio;
      }
      
      /**
       * Creates new form TelaRelatorio
       */
      public TelaRelatorio(java.awt.Frame parent, boolean modal, String s) {
            super(parent, modal);
            relatorio = s;
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea = new javax.swing.JTextArea();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setPreferredSize(new java.awt.Dimension(400, 300));
            setResizable(false);

            jTextArea.setColumns(20);
            jTextArea.setRows(5);
            jTextArea.setText(relatorio);
            jScrollPane1.setViewportView(jTextArea);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addContainerGap())
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JTextArea jTextArea;
      // End of variables declaration//GEN-END:variables
}
